### ISSUE TITLE
Virtuali biblioteka

### ISSUE THREAD

**Issue by Pawka** [vilniusphp/home#22]
Nariai turi galimybę paskelbti tinklapyje kokias knygas turi. Kiti, matydami sau patinkančią knygą gali siųsti užklausimus pasiskolinti konkrečią knygą.

Case'ai:
- Knygų sąrašas.
- Knygos įvedimas (gerai būtų su papildoma informacija, url į knygos oficialų puslapį, nuotrauka, tagai, etc.).
- Užklausimas paskolinti knygą. Savininko informacimas email'u, SMS (via [Twilio](www.twilio.com)) ar pan. Užklausų gali būti daug.
- Knygos skolinimas. Pakeičiamas knygos statusas į "paskolinta", išsaugoma kam paskolinta. Savininkas pats renkasi kam skolinti :-)

Daugiau minčių?

**Comment by podolskis** [comment]
Graži inciatyva, bet manau, kad reikia uždaryti šį issue.
