### ISSUE TITLE
Info apie Slack

### ISSUE THREAD

**Issue by rommaz** [vilniusphp/home#33]
Įdėti informaciją apie Slack kanalą ir kaip prisijungti. Jei Slack bus pagrindinė bendruomenės bendravimo tarp susitikimų vieta - galbūt info apie tai reikėtų patalpinti net pirmame puslapyje.

**Comment by podolskis** [comment]
Puikus pasiulymas. Siulau iš karto papildyti puslapį APIE, kur apie tai minima. Ar sulauksime PR?

**Comment by Pawka** [comment]
Manau kaip tik pagrindiniame turėtų būti ši informacija. Vienam iš blokų. Pvz. kairėj.

**Comment by podolskis** [comment]
Papildžiau about puslapį linkais. https://uglt.herokuapp.com -  nebeveikia, todėl reikia kito būdo įdėti slacko integraciją.

**Comment by rommaz** [comment]
http://rauchg.com/slackin/ aprašyme yra neblogas invite widgetas, gal jį reikėtų įsidėti prie grupės aprašymo.

**Comment by kuusas** [comment]
Jau veikia https://uglt.herokuapp.com ;)

**Comment by podolskis** [comment]
Šiandien įmesiu. Laukiau kol atkels :)

**Comment by kuusas** [comment]
@rommaz mūsiškis https://uglt.herokuapp.com tuo pagrindu ir padarytas.

**Comment by rommaz** [comment]
@kuusas Kaip suprantu, uglt padaryta remiantis aprašymo 1-me punkte pateiktu Landing page'u. Aš siūlau į puslapį įdėti 2-ame punte minimą mygtuką/widget'ą.

**Comment by podolskis** [comment]
https://www.dropbox.com/s/3vfb5nc7hgvsvzw/Screenshot%202015-10-15%2015.17.58.png?dl=0 @Pawka taip - ok?

**Comment by Pawka** [comment]
Reikia išlygiuoti.
